#!/bin/sh
#
# tools/ant-cl/plot-diag - Plot the output of  ant-cl -D >file
#
# Written 2012 by Werner Almesberger
# Copyright 2012 Werner Almesberger
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#

if [ -z "$1" -o ! -r "$1" ]; then
	echo "usage: $0 file" 1>&2
	exit 1
fi
gnuplot -p \
    -e 'set style data lines' \
    -e 'unset key' \
    -e "plot '$1' using 0:2, '$1' using 0:3, '$1' using 0:4, '$1' using 0:5,
   '$1' using 0:2 with impulses lt 7'"
